<?php
/**
 * @contact huangzhwork@gmail.com
 * @license https://github.com/huangzhhui/github-bot/blob/master/LICENSE
 */

return [
    'env' => env('APP_ENV', 'test'),
    'debug' => env('APP_DEBUG', false),
    'version' => '1.0',
    'autoInitBean' => true,
    'bootScan' => [],
    'excludeScan' => [],
    'github' => [
        'user_agent' => env('GITHUB_USER_AGENT', 'github-bot'),
        'access_token' => env('GITHUB_ACCESS_TOKEN', ''),
        'webhook' => [
            'secret' => env('GITHUB_WEBHOOK_SECRET', ''),
        ],
        'debug' => [
            'auth' => env('GITHUB_DEBUG_AUTH', ''),
        ],
        'merge' => [
            'method' => env('GITHUB_MERGE_METHOD', 'squash'),
        ],
        'release' => [
            // The prefix of pull request title that use to classified into the different part of release content.
            'message_cate' => [
                'added' => ['feat:', 'feature:', 'add:'],
                'changed' => ['change:', 'refactor:', 'modify:'],
                'fixed' => ['fix:', 'fixed:'],
                'deprecated' => ['deprecated:'],
                'removed' => ['remove:', 'delete:'],
            ],
            'message_template' => '@configs/templates/release.php',
            'repository_alias' => [
                'pipeline' => 'swoft-cloud/swoft-pipeline',
                'view' => 'swoft-cloud/swoft-view',
                'http-server' => 'swoft-cloud/swoft-http-server',
                'websocket-server' => 'swoft-cloud/swoft-websocket-server',
                'task' => 'swoft-cloud/swoft-task',
                'session' => 'swoft-cloud/swoft-session',
                'service-governance' => 'swoft-cloud/swoft-service-governance',
                'rpc-server' => 'swoft-cloud/swoft-rpc-server',
                'rpc-client' => 'swoft-cloud/swoft-rpc-client',
                'rpc' => 'swoft-cloud/swoft-rpc',
                'redis' => 'swoft-cloud/swoft-redis',
                'process' => 'swoft-cloud/swoft-process',
                'memory' => 'swoft-cloud/swoft-memory',
                'i18n' => 'swoft-cloud/swoft-i18n',
                'http-client' => 'swoft-cloud/swoft-http-client',
                'http-message' => 'swoft-cloud/swoft-http-message',
                'devtool' => 'swoft-cloud/swoft-devtool',
                'db' => 'swoft-cloud/swoft-db',
                'data-parser' => 'swoft-cloud/swoft-data-parser',
                'console' => 'swoft-cloud/swoft-console',
                'cache' => 'swoft-cloud/swoft-cache',
                'trace' => 'swoft-cloud/swoft-trace',
                'queue' => 'swoft-cloud/swoft-queue',
                'whoops' => 'swoft-cloud/swoft-whoops',
                'log' => 'swoft-cloud/swoft-log',
                'auth' => 'swoft-cloud/swoft-auth',
                'swagger' => 'swoft-cloud/swoft-swagger',
                'framework' => 'swoft-cloud/swoft-framework',
                'process' => 'swoft-cloud/swoft-process',
                'error-handler' => 'swoft-cloud/swoft-error-handler',
            ],
        ],
        'distribute' => [
            // Sponsor repos, only comment in this repos issue or pull request the command will be execute.
            'repositories' => [
                'huangzhhui/bot-test',
                'huangzhhui/github-bot',
                'swoft-cloud/swoft-component',
            ],
            // Components distribute mapping.
            'distribute_mapping' => [
                'src/pipeline' => 'swoft-cloud/swoft-pipeline',
                'src/view' => 'swoft-cloud/swoft-view',
                'src/http-server' => 'swoft-cloud/swoft-http-server',
                'src/websocket-server' => 'swoft-cloud/swoft-websocket-server',
                'src/task' => 'swoft-cloud/swoft-task',
                'src/session' => 'swoft-cloud/swoft-session',
                'src/service-governance' => 'swoft-cloud/swoft-service-governance',
                'src/rpc-server' => 'swoft-cloud/swoft-rpc-server',
                'src/rpc-client' => 'swoft-cloud/swoft-rpc-client',
                'src/rpc' => 'swoft-cloud/swoft-rpc',
                'src/redis' => 'swoft-cloud/swoft-redis',
                'src/process' => 'swoft-cloud/swoft-process',
                'src/memory' => 'swoft-cloud/swoft-memory',
                'src/i18n' => 'swoft-cloud/swoft-i18n',
                'src/http-client' => 'swoft-cloud/swoft-http-client',
                'src/http-message' => 'swoft-cloud/swoft-http-message',
                'src/devtool' => 'swoft-cloud/swoft-devtool',
                'src/db' => 'swoft-cloud/swoft-db',
                'src/data-parser' => 'swoft-cloud/swoft-data-parser',
                'src/console' => 'swoft-cloud/swoft-console',
                'src/cache' => 'swoft-cloud/swoft-cache',
                'src/trace' => 'swoft-cloud/swoft-trace',
                'src/queue' => 'swoft-cloud/swoft-queue',
                'src/whoops' => 'swoft-cloud/swoft-whoops',
                'src/log' => 'swoft-cloud/swoft-log',
                'src/auth' => 'swoft-cloud/swoft-auth',
                'src/swagger' => 'swoft-cloud/swoft-swagger',
                'src/framework' => 'swoft-cloud/swoft-framework',
                'src/process' => 'swoft-cloud/swoft-process',
                'src/error-handler' => 'swoft-cloud/swoft-error-handler',
            ],
        ],
    ],
];
